# Generated by Django 3.2.3 on 2021-05-17 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterInfo',
            fields=[
                ('ID', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('location', models.CharField(max_length=30, verbose_name='地理位置')),
                ('date', models.CharField(max_length=30, verbose_name='日期')),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='经度')),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='纬度')),
                ('depth', models.IntegerField(verbose_name='震源深度')),
                ('magnitude', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='震级')),
                ('reportingUnit', models.CharField(max_length=30, verbose_name='上报单位')),
            ],
        ),
        migrations.CreateModel(
            name='MissingStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30, verbose_name='日期')),
                ('location', models.CharField(max_length=30, verbose_name='失踪地点')),
                ('number', models.IntegerField(verbose_name='失踪人数')),
                ('reportingUnit', models.CharField(max_length=30, verbose_name='上报单位')),
                ('earthquakeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.disasterinfo')),
            ],
        ),
        migrations.CreateModel(
            name='InjuredStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30, verbose_name='日期')),
                ('location', models.CharField(max_length=30, verbose_name='受伤地点')),
                ('number', models.IntegerField(verbose_name='受伤人数')),
                ('reportingUnit', models.CharField(max_length=30, verbose_name='上报单位')),
                ('earthquakeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.disasterinfo')),
            ],
        ),
        migrations.CreateModel(
            name='DeathStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30, verbose_name='日期')),
                ('location', models.CharField(max_length=30, verbose_name='死亡地点')),
                ('number', models.IntegerField(verbose_name='死亡人数')),
                ('reportingUnit', models.CharField(max_length=30, verbose_name='上报单位')),
                ('earthquakeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.disasterinfo')),
            ],
        ),
    ]
